// Icon mappings for Hero Icons v2 compatibility
import {
  ArrowTrendingUpIcon,
  ArrowTrendingDownIcon,
  TruckIcon,
  ArrowDownTrayIcon,
  MagnifyingGlassPlusIcon,
  MagnifyingGlassMinusIcon,
  ChartBarIcon,
  ClockIcon,
  MapIcon,
  HomeIcon,
  UserCircleIcon,
  BellIcon,
  Cog6ToothIcon,
  EyeIcon,
  ExclamationTriangleIcon,
  CheckCircleIcon,
  XMarkIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  PlusIcon,
  MinusIcon,
  PencilIcon,
  TrashIcon,
  FunnelIcon,
  MagnifyingGlassIcon,
  ArrowPathIcon,
  DocumentIcon,
  ShareIcon,
  PrinterIcon,
  CubeIcon,
  BoltIcon,
  ShieldCheckIcon,
  ServerIcon,
  CpuChipIcon,
  Bars3Icon,
  XCircleIcon,
  InformationCircleIcon,
} from '@heroicons/react/24/outline';

// Export with the names your components expect
export const ArrowTrendingUpIcon = ArrowTrendingUpIcon;
export const ArrowTrendingDownIcon = ArrowTrendingDownIcon;
export const TrainIcon = TruckIcon; // Using TruckIcon replacement
export const DownloadIcon = ArrowDownTrayIcon;
export const ZoomInIcon = MagnifyingGlassPlusIcon;
export const ZoomOutIcon = MagnifyingGlassMinusIcon;

// Export all other icons as they are
export {
  ArrowTrendingUpIcon,
  ArrowTrendingDownIcon,
  TruckIcon,
  ArrowDownTrayIcon,
  MagnifyingGlassPlusIcon,
  MagnifyingGlassMinusIcon,
  ChartBarIcon,
  ClockIcon,
  MapIcon,
  HomeIcon,
  UserCircleIcon,
  BellIcon,
  Cog6ToothIcon,
  EyeIcon,
  ExclamationTriangleIcon,
  CheckCircleIcon,
  XMarkIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  PlusIcon,
  MinusIcon,
  PencilIcon,
  TrashIcon,
  FunnelIcon,
  MagnifyingGlassIcon,
  ArrowPathIcon,
  DocumentIcon,
  ShareIcon,
  PrinterIcon,
  CubeIcon,
  BoltIcon,
  ShieldCheckIcon,
  ServerIcon,
  CpuChipIcon,
  Bars3Icon,
  XCircleIcon,
  InformationCircleIcon,
};

export default {
  ArrowTrendingUpIcon,
  ArrowTrendingDownIcon,
  TrainIcon,
  DownloadIcon,
  ZoomInIcon,
  ZoomOutIcon,
  ChartBarIcon,
  ClockIcon,
  MapIcon,
  HomeIcon,
  UserCircleIcon,
  BellIcon,
  Cog6ToothIcon,
  EyeIcon,
  ExclamationTriangleIcon,
  CheckCircleIcon,
  XMarkIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  PlusIcon,
  MinusIcon,
  PencilIcon,
  TrashIcon,
  FunnelIcon,
  MagnifyingGlassIcon,
  ArrowPathIcon,
  DocumentIcon,
  ShareIcon,
  PrinterIcon,
  CubeIcon,
  BoltIcon,
  ShieldCheckIcon,
  ServerIcon,
  CpuChipIcon,
  Bars3Icon,
  XCircleIcon,
  InformationCircleIcon,
};